<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="POU_Clamp" Id="{1f4ba244-669d-4445-be61-dc452ae93b0d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM POU_Clamp
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU_Clamp">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>