<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="POU_Lubrication" Id="{3a0089b1-665f-404c-aeec-fa8a66974b1b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM POU_Lubrication
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU_Lubrication">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>